baseURL = "https://quellwood.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Quellwood"
[markup.goldmark.renderer]
unsafe = true
